### ISSUE TITLE
Optionally get reporter name from environment

### ISSUE THREAD

**Issue by Andreas-Hjortland** [wix/mocha-env-reporter#3]
Would it be possible to have an environment variable which explicitly told which reporter to use?

Something like 

``` javascript
'use strict';

var reporter = process.env.mocha_reporter;
var builtInReporters = require('mocha').reporters;
if(!reporter) {
     // keep this for backwards compatibility
    module.exports = (process.env.BUILD_NUMBER || process.env.TEAMCITY_VERSION) ? require('mocha-teamcity-reporter') : builtInReporters.spec;
} else if(builtInReporters.hasOwnProperty(reporter)) {
    module.exports = builtInReporters[reporter];
} else {
    module.exports = require(reporter);
}
```

Then we could set the reporter using the environment variable mocha_reporter (e.g. for the dot reporter: `mocha_reporter=dot mocha -r mocha-env-reporter`)
This would make this plugin useful in the case where we use another CI-solution like jenkins or bamboo.

**Comment by amir-arad** [comment]
sounds good. will do.

**Comment by Andreas-Hjortland** [comment]
If you want, I can just send a pull request of this change, because I have forked the repository and already made it.

**Comment by amir-arad** [comment]
@Andreas-Hjortland please do
